"""ExemplarStore — manage canonical "good outputs" per content-creation skill.

An exemplar is a piece of finished work the user has explicitly ratified:
it's what good looks like for this skill, in this user's voice, on this
kind of task.

Per L21: the `is_synthetic` flag distinguishes natural exemplars (from
real user iterations) from synthetic ones (generated by the edge-case
battery). The split lets calibration detect overfit-to-synthetic.

Sprint 7 will add backend-conditional vector embedding for similarity
retrieval; for now, the store is purely CRUD + filtering.
"""

from __future__ import annotations

import logging
from typing import Any

from sqlmodel import select

from agent_core.state.db import Database
from agent_core.state.models import Exemplar

logger = logging.getLogger(__name__)


class ExemplarStore:
    """CRUD + counting for content-creation exemplars."""

    def __init__(self, db: Database) -> None:
        self.db = db

    # ── Mutators ────────────────────────────────────────────────────────────

    def add(
        self,
        *,
        skill: str,
        content: str,
        title: str | None = None,
        source_iteration_id: str | None = None,
        is_synthetic: bool = False,
        metadata: dict[str, Any] | None = None,
    ) -> Exemplar:
        """Persist a new exemplar. Typically called by Iterations.ratify(),
        but the chat layer can also call directly when the user pastes a
        finished example for the agent to learn from."""
        ex = Exemplar(
            skill=skill,
            content=content,
            title=title,
            source_iteration_id=source_iteration_id,
            is_synthetic=is_synthetic,
            metadata_json=metadata,
        )
        with self.db.session() as s:
            s.add(ex)
            s.commit()
            s.refresh(ex)
        logger.info(
            "exemplar added: skill=%s id=%s synthetic=%s",
            skill,
            ex.id[:8],
            is_synthetic,
        )
        return ex

    def remove(self, exemplar_id: str) -> None:
        with self.db.session() as s:
            ex = s.get(Exemplar, exemplar_id)
            if ex is None:
                raise ValueError(f"exemplar {exemplar_id!r} not found")
            s.delete(ex)
            s.commit()

    # ── Queries ─────────────────────────────────────────────────────────────

    def get_by_id(self, exemplar_id: str) -> Exemplar | None:
        with self.db.session() as s:
            return s.get(Exemplar, exemplar_id)

    def get_by_skill(
        self,
        skill: str,
        *,
        limit: int | None = None,
        include_synthetic: bool = True,
    ) -> list[Exemplar]:
        """Active exemplars for ``skill``, newest first."""
        with self.db.session() as s:
            stmt = (
                select(Exemplar).where(Exemplar.skill == skill).order_by(Exemplar.created_at.desc())
            )
            rows = list(s.exec(stmt).all())
        if not include_synthetic:
            rows = [r for r in rows if not r.is_synthetic]
        if limit is not None:
            rows = rows[:limit]
        return rows

    def count_total(self, skill: str) -> int:
        with self.db.session() as s:
            return len(list(s.exec(select(Exemplar).where(Exemplar.skill == skill)).all()))

    def count_natural(self, skill: str) -> int:
        return sum(1 for e in self.get_by_skill(skill) if not e.is_synthetic)

    def count_synthetic(self, skill: str) -> int:
        return sum(1 for e in self.get_by_skill(skill) if e.is_synthetic)


__all__ = ["ExemplarStore"]
