"""initial schema

Revision ID: 90861088948c
Revises:
Create Date: 2026-05-02 22:02:54.115004

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  — for sqlmodel.AutoString and friends in autogenerate
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90861088948c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("attempts_count", sa.Integer(), nullable=False),
        sa.Column("ratifications_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_ratifications", sa.Integer(), nullable=False),
        sa.Column("autonomous_mode", sa.Boolean(), nullable=False),
        sa.Column("autonomous_mode_threshold", sa.Float(), nullable=False),
        sa.Column("last_calibrated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calibration", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calibration_autonomous_mode"), ["autonomous_mode"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_calibration_skill"), ["skill"], unique=True)

    op.create_table(
        "identity",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instance_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("persona_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("persona_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("principal_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("principal_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestion_run",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("items_seen", sa.Integer(), nullable=False),
        sa.Column("items_inserted", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("items_skipped", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("error_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingestion_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingestion_run_source_kind"), ["source_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ingestion_run_started_at"), ["started_at"], unique=False
        )

    op.create_table(
        "intercom_message",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("msg_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "delivered",
                "acknowledged",
                name="intercomstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("intercom_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_intercom_message_recipient"), ["recipient"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_intercom_message_sender"), ["sender"], unique=False)
        batch_op.create_index(batch_op.f("ix_intercom_message_sent_at"), ["sent_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_intercom_message_state"), ["state"], unique=False)

    op.create_table(
        "learning_rule",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill_tags", sa.JSON(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("context", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("superseded_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["learning_rule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learning_rule", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_rule_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metric", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metric_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_metric_recorded_at"), ["recorded_at"], unique=False)

    op.create_table(
        "obligation",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "inbox",
                "in_progress",
                "waiting",
                "done",
                name="obligationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "owner",
            sa.Enum("agent", "principal", name="obligationowner", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "inbound_email",
                "principal_chat",
                "peer_message",
                "cron_trigger",
                "agent_decomposition",
                "manual",
                name="obligationsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completion_criteria", sa.JSON(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("obligation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_obligation_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligation_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligation_owner"), ["owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligation_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligation_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligation_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_obligation_title"), ["title"], unique=False)

    op.create_table(
        "peer",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instance_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("dcos", "ikb", "other", name="peerrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("endpoint_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("peer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_peer_instance_name"), ["instance_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_peer_role"), ["role"], unique=False)

    op.create_table(
        "quality_audit",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audit_level", sa.Integer(), nullable=False),
        sa.Column("auditor_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("primary_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sampling_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audited_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quality_audit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quality_audit_audit_level"), ["audit_level"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quality_audit_audited_at"), ["audited_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quality_audit_passed"), ["passed"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_quality_audit_subject_model"), ["subject_model"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quality_audit_task_type"), ["task_type"], unique=False)

    op.create_table(
        "quality_score",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("audit_level", sa.Integer(), nullable=False),
        sa.Column("subject_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_audited", sa.Integer(), nullable=False),
        sa.Column("running_sum", sa.Float(), nullable=False),
        sa.Column("running_avg", sa.Float(), nullable=False),
        sa.Column("last_n_avg", sa.Float(), nullable=True),
        sa.Column("strikes", sa.Integer(), nullable=False),
        sa.Column("is_delegated", sa.Boolean(), nullable=False),
        sa.Column("last_audit_at", sa.DateTime(), nullable=True),
        sa.Column("last_undelegated_at", sa.DateTime(), nullable=True),
        sa.Column("last_restored_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quality_score", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quality_score_audit_level"), ["audit_level"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quality_score_is_delegated"), ["is_delegated"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quality_score_subject_model"), ["subject_model"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quality_score_task_type"), ["task_type"], unique=False)

    op.create_table(
        "session",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("obligation_ids_touched", sa.JSON(), nullable=True),
        sa.Column("skills_invoked", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_started_at"), ["started_at"], unique=False)

    op.create_table(
        "template",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("placeholders", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_template_skill"), ["skill"], unique=False)

    op.create_table(
        "thought",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thought", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thought_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_thought_fingerprint"), ["fingerprint"], unique=False)

    op.create_table(
        "action_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "action_class",
            sa.Enum(
                "read",
                "write_internal",
                "ob_update",
                "cross_agent_message",
                "calendar_read",
                "ingest",
                "capture_learning_candidate",
                "send_email_external",
                "content_publish",
                "calendar_invite_external",
                "modify_people_data",
                "install_skill",
                "secret_access",
                "finance",
                name="actionclass",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "succeeded",
                "failed",
                "deferred",
                "blocked_by_policy",
                name="actionoutcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_log_action_class"), ["action_class"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_log_obligation_id"), ["obligation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_log_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_action_log_outcome"), ["outcome"], unique=False)

    op.create_table(
        "completion_check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("criterion", sa.JSON(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("completion_check", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_completion_check_checked_at"), ["checked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_completion_check_obligation_id"), ["obligation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_completion_check_passed"), ["passed"], unique=False)

    op.create_table(
        "correction_candidate",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detected_correction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("inferred_skill_tags", sa.JSON(), nullable=True),
        sa.Column("source_session", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "promoted",
                "rejected",
                "expired",
                name="correctioncandidatestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("promoted_to_rule_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promoted_to_rule_id"],
            ["learning_rule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("correction_candidate", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_correction_candidate_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_correction_candidate_status"), ["status"], unique=False
        )

    op.create_table(
        "delegation",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("delegated_to", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "completed",
                "cancelled",
                name="delegationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_check_in_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("delegation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_delegation_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_delegation_delegated_to"), ["delegated_to"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_delegation_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_delegation_status"), ["status"], unique=False)

    op.create_table(
        "incident",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="incidentseverity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "acknowledged",
                "resolved",
                name="incidentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("related_obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["related_obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incident_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_incident_related_obligation_id"), ["related_obligation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_incident_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_incident_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_incident_title"), ["title"], unique=False)

    op.create_table(
        "intercom_ack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("acked_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("acked_at", sa.DateTime(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["intercom_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("intercom_ack", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_intercom_ack_acked_at"), ["acked_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_intercom_ack_acked_by"), ["acked_by"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_intercom_ack_message_id"), ["message_id"], unique=False
        )

    op.create_table(
        "iteration",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_input", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.JSON(), nullable=True),
        sa.Column("corrections", sa.JSON(), nullable=True),
        sa.Column("final_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "ratified",
                "abandoned",
                name="iterationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ratified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("iteration", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_iteration_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_iteration_is_synthetic"), ["is_synthetic"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_iteration_skill"), ["skill"], unique=False)
        batch_op.create_index(batch_op.f("ix_iteration_status"), ["status"], unique=False)

    op.create_table(
        "obligation_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "created",
                "status_changed",
                "plan_developed",
                "step_executed",
                "completion_checked",
                "closed",
                "reopened",
                "comment",
                name="obligationeventkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("obligation_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_obligation_event_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_obligation_event_obligation_id"), ["obligation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_obligation_event_occurred_at"), ["occurred_at"], unique=False
        )

    op.create_table(
        "plan",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planning",
                "executing",
                "blocked",
                "verified",
                name="planstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_obligation_id"), ["obligation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_plan_status"), ["status"], unique=False)

    op.create_table(
        "rule_firing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("was_overridden", sa.Boolean(), nullable=False),
        sa.Column("fired_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["learning_rule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rule_firing", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_firing_fired_at"), ["fired_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_rule_firing_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rule_firing_skill"), ["skill"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rule_firing_was_overridden"), ["was_overridden"], unique=False
        )

    op.create_table(
        "run_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("obligation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trigger", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_run_log_obligation_id"), ["obligation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_run_log_skill"), ["skill"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_log_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_log_success"), ["success"], unique=False)

    op.create_table(
        "thought_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thought_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_until", sa.DateTime(), nullable=True),
        sa.Column("authority", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thought_id"],
            ["thought.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thought_source", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thought_source_fetched_at"), ["fetched_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_thought_source_source_kind"), ["source_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_thought_source_thought_id"), ["thought_id"], unique=False
        )

    op.create_table(
        "exemplar",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_iteration_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_iteration_id"],
            ["iteration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exemplar", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exemplar_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_exemplar_is_synthetic"), ["is_synthetic"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exemplar_skill"), ["skill"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exemplar", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exemplar_skill"))
        batch_op.drop_index(batch_op.f("ix_exemplar_is_synthetic"))
        batch_op.drop_index(batch_op.f("ix_exemplar_created_at"))

    op.drop_table("exemplar")
    with op.batch_alter_table("thought_source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thought_source_thought_id"))
        batch_op.drop_index(batch_op.f("ix_thought_source_source_kind"))
        batch_op.drop_index(batch_op.f("ix_thought_source_fetched_at"))

    op.drop_table("thought_source")
    with op.batch_alter_table("run_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_log_success"))
        batch_op.drop_index(batch_op.f("ix_run_log_started_at"))
        batch_op.drop_index(batch_op.f("ix_run_log_skill"))
        batch_op.drop_index(batch_op.f("ix_run_log_obligation_id"))

    op.drop_table("run_log")
    with op.batch_alter_table("rule_firing", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_firing_was_overridden"))
        batch_op.drop_index(batch_op.f("ix_rule_firing_skill"))
        batch_op.drop_index(batch_op.f("ix_rule_firing_rule_id"))
        batch_op.drop_index(batch_op.f("ix_rule_firing_fired_at"))

    op.drop_table("rule_firing")
    with op.batch_alter_table("plan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_status"))
        batch_op.drop_index(batch_op.f("ix_plan_obligation_id"))

    op.drop_table("plan")
    with op.batch_alter_table("obligation_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_obligation_event_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_obligation_event_obligation_id"))
        batch_op.drop_index(batch_op.f("ix_obligation_event_kind"))

    op.drop_table("obligation_event")
    with op.batch_alter_table("iteration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_iteration_status"))
        batch_op.drop_index(batch_op.f("ix_iteration_skill"))
        batch_op.drop_index(batch_op.f("ix_iteration_is_synthetic"))
        batch_op.drop_index(batch_op.f("ix_iteration_created_at"))

    op.drop_table("iteration")
    with op.batch_alter_table("intercom_ack", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intercom_ack_message_id"))
        batch_op.drop_index(batch_op.f("ix_intercom_ack_acked_by"))
        batch_op.drop_index(batch_op.f("ix_intercom_ack_acked_at"))

    op.drop_table("intercom_ack")
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_title"))
        batch_op.drop_index(batch_op.f("ix_incident_status"))
        batch_op.drop_index(batch_op.f("ix_incident_severity"))
        batch_op.drop_index(batch_op.f("ix_incident_related_obligation_id"))
        batch_op.drop_index(batch_op.f("ix_incident_occurred_at"))

    op.drop_table("incident")
    with op.batch_alter_table("delegation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_delegation_status"))
        batch_op.drop_index(batch_op.f("ix_delegation_due_at"))
        batch_op.drop_index(batch_op.f("ix_delegation_delegated_to"))
        batch_op.drop_index(batch_op.f("ix_delegation_created_at"))

    op.drop_table("delegation")
    with op.batch_alter_table("correction_candidate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_correction_candidate_status"))
        batch_op.drop_index(batch_op.f("ix_correction_candidate_created_at"))

    op.drop_table("correction_candidate")
    with op.batch_alter_table("completion_check", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_completion_check_passed"))
        batch_op.drop_index(batch_op.f("ix_completion_check_obligation_id"))
        batch_op.drop_index(batch_op.f("ix_completion_check_checked_at"))

    op.drop_table("completion_check")
    with op.batch_alter_table("action_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_log_outcome"))
        batch_op.drop_index(batch_op.f("ix_action_log_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_action_log_obligation_id"))
        batch_op.drop_index(batch_op.f("ix_action_log_action_class"))

    op.drop_table("action_log")
    with op.batch_alter_table("thought", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thought_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_thought_created_at"))

    op.drop_table("thought")
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_template_skill"))

    op.drop_table("template")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_started_at"))

    op.drop_table("session")
    with op.batch_alter_table("quality_score", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_score_task_type"))
        batch_op.drop_index(batch_op.f("ix_quality_score_subject_model"))
        batch_op.drop_index(batch_op.f("ix_quality_score_is_delegated"))
        batch_op.drop_index(batch_op.f("ix_quality_score_audit_level"))

    op.drop_table("quality_score")
    with op.batch_alter_table("quality_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_audit_task_type"))
        batch_op.drop_index(batch_op.f("ix_quality_audit_subject_model"))
        batch_op.drop_index(batch_op.f("ix_quality_audit_passed"))
        batch_op.drop_index(batch_op.f("ix_quality_audit_audited_at"))
        batch_op.drop_index(batch_op.f("ix_quality_audit_audit_level"))

    op.drop_table("quality_audit")
    with op.batch_alter_table("peer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_peer_role"))
        batch_op.drop_index(batch_op.f("ix_peer_instance_name"))

    op.drop_table("peer")
    with op.batch_alter_table("obligation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_obligation_title"))
        batch_op.drop_index(batch_op.f("ix_obligation_status"))
        batch_op.drop_index(batch_op.f("ix_obligation_priority"))
        batch_op.drop_index(batch_op.f("ix_obligation_parent_id"))
        batch_op.drop_index(batch_op.f("ix_obligation_owner"))
        batch_op.drop_index(batch_op.f("ix_obligation_due_at"))
        batch_op.drop_index(batch_op.f("ix_obligation_created_at"))

    op.drop_table("obligation")
    with op.batch_alter_table("metric", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_metric_name"))

    op.drop_table("metric")
    with op.batch_alter_table("learning_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_rule_created_at"))

    op.drop_table("learning_rule")
    with op.batch_alter_table("intercom_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intercom_message_state"))
        batch_op.drop_index(batch_op.f("ix_intercom_message_sent_at"))
        batch_op.drop_index(batch_op.f("ix_intercom_message_sender"))
        batch_op.drop_index(batch_op.f("ix_intercom_message_recipient"))

    op.drop_table("intercom_message")
    with op.batch_alter_table("ingestion_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_run_started_at"))
        batch_op.drop_index(batch_op.f("ix_ingestion_run_source_kind"))

    op.drop_table("ingestion_run")
    op.drop_table("identity")
    with op.batch_alter_table("calibration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calibration_skill"))
        batch_op.drop_index(batch_op.f("ix_calibration_autonomous_mode"))

    op.drop_table("calibration")
    # ### end Alembic commands ###
